import { readFile, writeFile } from 'node:fs/promises';
import { gunzipSync, gzipSync } from 'node:zlib';
const data=JSON.parse(await readFile('data/current.json','utf8'));let transcripts=[];try{transcripts=JSON.parse(gunzipSync(await readFile('data/transcripts.json.gz'),'utf8')).documents||[]}catch{}
const byUrl=new Map(transcripts.map(x=>[String(x.url).split('#')[0],x]));
const lexicon=[['presupuesto',/presupuesto|estabilidad presupuestaria|deuda pública/i],['vivienda',/vivienda|alquiler|hipoteca/i],['sanidad',/sanidad|salud pública|hospital/i],['educación',/educación|universidad|escuela/i],['justicia',/justicia|judicial|tribunal/i],['igualdad',/igualdad|violencia machista|mujeres/i],['empleo',/empleo|trabajo|salario|laboral/i],['energía',/energía|clima|medio ambiente|renovable/i],['agricultura',/agricultura|pesca|ganadería/i],['migración',/migración|inmigración|frontera/i],['europa',/Unión Europea|europe[oa]|Bruselas/i],['defensa',/defensa|ejército|OTAN/i],['territorio',/autonomía|territorial|Cataluña|Euskadi/i]];
const evidence=[];for(const x of data.interventions){const source=byUrl.get(String(x.textUrl||'').split('#')[0]);const hay=`${x.title||''} ${x.topic||''} ${source?.text||''}`;const labels=lexicon.filter(([,re])=>re.test(hay)).map(([label])=>label);x.topicLabels=labels.length?labels:['procedimiento'];x.topicAnalysisVersion='lexicon-es-v1';if(source?.text){const needle=String(x.title||'').split(/\s+/).filter(w=>w.length>5)[0];const at=needle?source.text.toLocaleLowerCase('es').indexOf(needle.toLocaleLowerCase('es')):-1;const passage=source.text.slice(at>=0?Math.max(0,at-120):0,(at>=0?at:0)+360);evidence.push({interventionId:x.id,labels:x.topicLabels,passage,sourceUrl:source.url,method:'official_transcript_passage',version:'lexicon-es-v1'});}}
const daily=new Map(); const add=(deputyId,date)=>{if(!deputyId||!date)return null;const key=`${deputyId}|${date}`;if(!daily.has(key))daily.set(key,{deputyId,date,interventionTurns:0,interventionSeconds:0,nominalVoteEvents:0,remoteVoteEvents:0,evidenceKinds:[]});return daily.get(key)};const mins=(a,b)=>{if(!a||!b)return 0;const x=String(a).split(':').map(Number),y=String(b).split(':').map(Number);return Math.max(0,(y[0]*60+y[1])-(x[0]*60+x[1]))*60};for(const x of data.interventions){const s=data.sessions.find(v=>v.id===x.sessionId);const r=add(x.deputyId,s?.date);if(r){r.interventionTurns++;r.interventionSeconds+=mins(x.start,x.end);if(!r.evidenceKinds.includes('timed_intervention'))r.evidenceKinds.push('timed_intervention');}}try{const full=JSON.parse(gunzipSync(await readFile('data/votes-full.json.gz'),'utf8'));const ids=new Map(data.deputies.map(d=>[d.name.toLocaleLowerCase('es'),d.id]));for(const v of full.votes){const date=v.payload?.informacion?.fecha;for(const x of v.payload?.votaciones||[]){const r=add(ids.get(String(x.diputado||'').toLocaleLowerCase('es')),date);if(r){r.nominalVoteEvents++;if(String(x.asiento)==='-1')r.remoteVoteEvents++;if(!r.evidenceKinds.includes('nominal_vote'))r.evidenceKinds.push('nominal_vote');}}}}catch{}
const dailyPresenceSummaries=[...daily.values()].sort((a,b)=>a.date.localeCompare(b.date)||a.deputyId.localeCompare(b.deputyId));
await writeFile('data/topic-evidence.json',JSON.stringify({meta:{generatedAt:new Date().toISOString(),version:'lexicon-es-v1',caveat:'Labels are multi-label discovery aids; supporting passages are retained for review.'},evidence},null,2));await writeFile('data/daily-presence-summaries.json.gz',gzipSync(JSON.stringify({meta:{generatedAt:new Date().toISOString(),version:'daily-evidence-v1'},summaries:dailyPresenceSummaries})));await writeFile('data/current.json',JSON.stringify(data,null,2));console.log(`analysed ${data.interventions.length} interventions; ${evidence.length} have transcript passages; ${dailyPresenceSummaries.length} daily summaries`);
