import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const raw=[...JSON.parse(await readFile('data/raw/deputies-19','utf8')), ...JSON.parse(await readFile('data/raw/deputies-25','utf8'))];
const interventionRaw=JSON.parse(await readFile('data/raw/interventions-19','utf8'));
let identityRows=[]; try { identityRows=JSON.parse(await readFile('data/raw/deputy-identities.json','utf8')).records||[]; } catch {}
let substitutionRows=[]; try { substitutionRows=JSON.parse(await readFile('data/raw/substitutions.json','utf8')).records||[]; } catch {}
let profileDocuments=[]; try { profileDocuments=JSON.parse(await readFile('data/profile-documents.json','utf8')).documents||[]; } catch {}
let voteRows=[]; try { voteRows=(JSON.parse(await readFile('data/votes.json','utf8')).votes||[]).map(v=>({id:v.id,resultUrl:v.url,payload:v.payload,individual:[]})); } catch { /* vote import is optional and logged separately */ }
let formalBodyMemberships=[]; let bodyManifest={}; try{bodyManifest=JSON.parse(await readFile('data/bodies/manifest.json','utf8'));}catch{} for(const bodyName of ['mesa','junta-portavoces','diputacion-permanente']){try{const status=bodyManifest.sources?.find(x=>x.name===bodyName)?.validationStatus||'unverified_response'; if(status==='duplicate_response_possible_parameter_ignored') continue; const payload=JSON.parse(await readFile(`data/bodies/${bodyName}.json`,'utf8'));formalBodyMemberships.push(...(payload.data||[]).map(x=>({bodyId:bodyName,deputyName:x.apellidosNombre,role:x.descCargo,group:x.siglas,from:x.fechaAltaFormat||null,to:x.fechaBajaFormat||null,officialDeputyUrl:x.urlFichaDiputado||null,evidenceType:'formal_composition_export',validationStatus:status})));}catch{/* source unavailable */}}
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const deputies=[...new Map(raw.map(x=>[slug(x.NOMBRE),{id:slug(x.NOMBRE),officialName:x.NOMBRE,name:x.NOMBRE,group:x.GRUPOPARLAMENTARIO||null,constituency:x.CIRCUNSCRIPCION||null,electoralFormation:x.FORMACIONELECTORAL||null,service:{from:x.FECHAALTA||x.FECHACONDICIONPLENA||null,to:x.FECHABAJA||null},biography:x.BIOGRAFIA||null,sourceUrl:'https://www.congreso.es/es/opendata/diputados',identityQuality:'name_slug_pending_official_id_crosswalk'}])).values()];
const byName=new Map(deputies.map(d=>[d.name.toLocaleLowerCase('es'),d.id]));
const identityByName=new Map(identityRows.map(x=>[String(x.apellidosNombre||'').toLocaleLowerCase('es'),x]));
for(const d of deputies){const x=identityByName.get(d.name.toLocaleLowerCase('es')); if(x){d.officialId=String(x.codParlamentario);d.profileUrl=`https://www.congreso.es/es/busqueda-de-diputados?p_p_id=diputadomodule&p_p_lifecycle=0&p_p_state=normal&mostrarFicha=true&codParlamentario=${d.officialId}&idLegislatura=15`;d.identityQuality='official_id_search_endpoint';}}
const officialIds=new Map();
const votePayloads=voteRows.map(v=>{const items=v.payload?.votaciones||[];return {...v,sessionNumber:v.payload?.informacion?.sesion,date:v.payload?.informacion?.fecha,individual:items.map(x=>({deputyId:byName.get(String(x.diputado||'').toLocaleLowerCase('es'))||null,name:x.diputado,choice:x.voto,seat:x.asiento,group:x.grupo}))};});
const attendanceEvents=votePayloads.flatMap(v=>v.individual.filter(x=>x.deputyId).map(x=>({id:`${v.id}-${x.deputyId}`,deputyId:x.deputyId,date:v.date,kind:x.seat==='-1'?'remote_participation':'in_person_participation',value:'recorded_vote',voteId:v.id,seat:x.seat,evidenceUrl:v.url}))); 
const sessions=[...new Map(interventionRaw.map(x=>{const [day,month,year]=String(x.SESION||'').split('/');return [`${x.ORGANO}-${year}-${month}-${day}`,{id:`${x.ORGANO}-${year}-${month}-${day}`,body:x.ORGANO,date:year&&month&&day?`${year}-${month}-${day}`:x.SESION,status:'intervention_indexed'}]})).values()];
const interventions=interventionRaw.map((x,i)=>{const speaker=String(x.ORADOR||'').replace(/\s*\([^)]*\)\s*$/,'').toLocaleLowerCase('es');const [day,month,year]=String(x.SESION||'').split('/');return {id:`intervention-${i+1}`,sessionId:`${x.ORGANO}-${year}-${month}-${day}`,deputyId:byName.get(speaker)||null,speaker:x.ORADOR,initiativeId:x.NUMEXPEDIENTE||null,title:x.OBJETO||x.OBJETOINICIATIVA||x.TIPOINICIATIVA||null,topic:x.SUPERTIPOINICIATIVA||x.TIPOINICIATIVA||'sin clasificar',start:x.INICIOINTERVENCION||null,end:x.FININTERVENCION||null,textUrl:x.ENLACETEXTOINTEGRO||null,clipUrl:x.ENLACEDESCARGADIRECTA||null,sourceUrl:x.ENLACEPDF||null,text:null,textStatus:'official_text_linked'};});
const bodies=[...new Set(interventionRaw.map(x=>x.ORGANO).filter(Boolean))].map(name=>({id:slug(name),name,sourceUrl:'https://www.congreso.es/es/opendata/organos',membershipStatus:'activity-derived'}));
const bodyActivity=[...new Map(interventionRaw.filter(x=>x.ORADOR).map(x=>[`${x.ORGANO}|${x.ORADOR}`,{bodyId:slug(x.ORGANO),deputyId:byName.get(String(x.ORADOR).replace(/\s*\([^)]*\)\s*$/,'').toLocaleLowerCase('es'))||null,deputyName:x.ORADOR,firstDate:x.SESION,lastDate:x.SESION,evidenceType:'intervention_in_body'}])).values()];
const initiatives=[...new Map(interventionRaw.filter(x=>x.NUMEXPEDIENTE||x.OBJETO||x.TIPOINICIATIVA).map(x=>[x.NUMEXPEDIENTE||`${x.TIPOINICIATIVA}|${x.OBJETO}`,{id:x.NUMEXPEDIENTE||slug(`${x.TIPOINICIATIVA}-${x.OBJETO}`),number:x.NUMEXPEDIENTE||null,title:x.OBJETO||x.OBJETOINICIATIVA||null,type:x.TIPOINICIATIVA||null,superType:x.SUPERTIPOINICIATIVA||null,authorLabel:x.AUTOR||null,firstSession:x.SESION,lastSession:x.SESION,sourceUrl:x.ENLACEPDF||x.ENLACETEXTOINTEGRO||null,source:'official_intervention_export'}])).values()];
for(const m of formalBodyMemberships){const match=String(m.officialDeputyUrl||'').match(/codParlamentario=([^&]+)/);const deputyId=byName.get(String(m.deputyName||'').toLocaleLowerCase('es'));if(deputyId&&match){officialIds.set(deputyId,match[1]);m.deputyId=deputyId;}}
for(const d of deputies){if(officialIds.has(d.id)){d.officialId=officialIds.get(d.id);d.profileUrl=`https://www.congreso.es/es/busqueda-de-diputados?p_p_id=diputadomodule&p_p_lifecycle=0&p_p_state=normal&mostrarFicha=true&codParlamentario=${d.officialId}&idLegislatura=XV`;d.identityQuality='official_id_crosswalk_from_body_export';}}
const servicePeriods=raw.map((x,i)=>({id:`service-${i+1}-${slug(x.NOMBRE)}`,deputyId:slug(x.NOMBRE),legislature:'XV',from:x.FECHAALTA||x.FECHACONDICIONPLENA||null,to:x.FECHABAJA||null,group:x.GRUPOPARLAMENTARIO||null,groupFrom:x.FECHAALTAENGRUPOPARLAMENTARIO||null,groupTo:x.FECHABAJAENGRUPOPARLAMENTARIO||null,evidenceType:'official_deputy_export'}));
const substitutions=substitutionRows.map((x,i)=>({id:`substitution-${i+1}`,legislature:'XV',substituteId:identityByName.get(String(x.apellidosNombre||'').toLocaleLowerCase('es'))?.codParlamentario||String(x.codParlamentario||''),substitutedId:x.dipSustituido?.codParlamentario||null,substituteName:x.apellidosNombre||null,substitutedName:x.dipSustituido?.apellidosNombre||null,from:x.fchAlta||null,to:x.fchBaja||null,source:'official_substitution_page'}));
const initiativeAuthorship=[...new Set(interventions.filter(x=>x.initiativeId&&x.deputyId).map(x=>`${x.initiativeId}|${x.deputyId}`))].map(k=>{const [initiativeId,deputyId]=k.split('|');return {initiativeId,deputyId,authorshipType:'speaker_attributed',evidence:'official_intervention_export'};});
let agendaItems=sessions.map(s=>({id:`agenda-${s.id}`,sessionId:s.id,title:`${s.body} ${s.date}`,status:'published_session_record',sourceUrl:'https://www.congreso.es/es/agenda'})); try { const imported=JSON.parse(await readFile('data/agenda.json','utf8')); if(imported.items?.length) agendaItems=imported.items; } catch {}
const mediaSegments=interventions.filter(x=>x.clipUrl).map(x=>({id:`media-${x.id}`,interventionId:x.id,sessionId:x.sessionId,deputyId:x.deputyId,url:x.clipUrl,kind:'official_downloadable_clip',durationSeconds:null,evidenceStatus:'link_only'}));
const sourceDocuments=[{id:'deputies-active',url:'https://www.congreso.es/es/opendata/diputados',retrievedAt:new Date().toISOString(),parserVersion:'build-current-v2',objectPath:'data/raw/deputies-19',recordCount:raw.length},{id:'deputies-former',url:'https://www.congreso.es/es/opendata/diputados',retrievedAt:new Date().toISOString(),parserVersion:'build-current-v2',objectPath:'data/raw/deputies-25',recordCount:JSON.parse(await readFile('data/raw/deputies-25','utf8')).length},{id:'interventions',url:'https://www.congreso.es/es/opendata/intervenciones',retrievedAt:new Date().toISOString(),parserVersion:'build-current-v2',objectPath:'data/raw/interventions-19',recordCount:interventionRaw.length}];
try { const agenda=JSON.parse(await readFile('data/agenda.json','utf8')); sourceDocuments.push({id:'agenda',url:'https://www.congreso.es/es/agenda',retrievedAt:new Date().toISOString(),parserVersion:agenda.meta?.parserVersion||'agenda-html-v1',objectPath:'data/agenda.json',recordCount:agenda.items?.length||0}); } catch {}
if(identityRows.length) sourceDocuments.push({id:'deputy-identities',url:'https://www.congreso.es/es/busqueda-de-diputados',retrievedAt:new Date().toISOString(),parserVersion:'deputy-search-v1',objectPath:'data/raw/deputy-identities.json',recordCount:identityRows.length}); if(substitutionRows.length) sourceDocuments.push({id:'substitutions',url:'https://www.congreso.es/es/diputados-sustituidos-y-sustitutos',retrievedAt:new Date().toISOString(),parserVersion:'substitutions-embedded-json-v1',objectPath:'data/raw/substitutions.json',recordCount:substitutionRows.length});
if(profileDocuments.length) sourceDocuments.push({id:'profile-documents',url:'https://www.congreso.es/es/busqueda-de-diputados',retrievedAt:new Date().toISOString(),parserVersion:'profile-link-index-v1',objectPath:'data/profile-documents.json',recordCount:profileDocuments.length});
for(const doc of sourceDocuments){try{const bytes=await readFile(doc.objectPath);doc.sha256=createHash('sha256').update(bytes).digest('hex');doc.bytes=bytes.length;}catch{doc.error='raw snapshot unavailable';}}
await writeFile('data/current.json',JSON.stringify({meta:{legislature:'XV',status:'current-legislature',generatedAt:new Date().toISOString(),coverage:`${deputies.length} deputies who are active or have served in XV; ${interventions.length} official intervention records, ${votePayloads.length} vote payloads, ${attendanceEvents.length} attendance events, ${initiatives.length} initiatives, ${substitutions.length} substitution records, ${profileDocuments.length} profile documents and ${formalBodyMemberships.length} formal body assignments indexed`,identityPolicy:'Official identifiers are retained when published; names are a reviewed fallback only.',denominators:{speakingDays:'days with at least one attributed intervention',evidencedMinutes:'sum of published intervention start/end intervals',voteParticipation:'individual rows present in imported nominal ballots',presence:'timestamped evidence events only'},gaps:['Complete official attendance register is not published in the imported sources','Committee composition endpoint responses require manual validation when commissions are constituted','Video seat observations remain unreviewed pilot evidence and never identify occupants automatically','Transcript text is linked to official documents; generated transcription is not substituted']},deputies,servicePeriods,substitutions,profileDocuments,bodies,bodyActivity,formalBodyMemberships,sessions,agendaItems,initiatives,initiativeAuthorship,interventions,mediaSegments,sourceDocuments,votes:votePayloads,presenceObservations:attendanceEvents},null,2)); console.log(`built ${deputies.length} deputies, ${interventions.length} interventions, ${initiatives.length} initiatives and ${votePayloads.length} votes`);
