import { readFile, writeFile } from 'node:fs/promises';
const raw=[...JSON.parse(await readFile('data/raw/deputies-19','utf8')), ...JSON.parse(await readFile('data/raw/deputies-25','utf8'))];
const interventionRaw=JSON.parse(await readFile('data/raw/interventions-19','utf8'));
let voteRows=[]; try { voteRows=(JSON.parse(await readFile('data/votes.json','utf8')).votes||[]).map(v=>({id:v.id,resultUrl:v.url,payload:v.payload,individual:[]})); } catch { /* vote import is optional and logged separately */ }
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const deputies=[...new Map(raw.map(x=>[slug(x.NOMBRE),{id:slug(x.NOMBRE),officialName:x.NOMBRE,name:x.NOMBRE,group:x.GRUPOPARLAMENTARIO||null,constituency:x.CIRCUNSCRIPCION||null,electoralFormation:x.FORMACIONELECTORAL||null,service:{from:x.FECHAALTA||x.FECHACONDICIONPLENA||null,to:x.FECHABAJA||null},biography:x.BIOGRAFIA||null,sourceUrl:'https://www.congreso.es/es/opendata/diputados',identityQuality:'name_slug_pending_official_id_crosswalk'}])).values()];
const byName=new Map(deputies.map(d=>[d.name.toLocaleLowerCase('es'),d.id]));
const votePayloads=voteRows.map(v=>{const items=v.payload?.votaciones||[];return {...v,sessionNumber:v.payload?.informacion?.sesion,date:v.payload?.informacion?.fecha,individual:items.map(x=>({deputyId:byName.get(String(x.diputado||'').toLocaleLowerCase('es'))||null,name:x.diputado,choice:x.voto,seat:x.asiento,group:x.grupo}))};});
const attendanceEvents=votePayloads.flatMap(v=>v.individual.filter(x=>x.deputyId).map(x=>({id:`${v.id}-${x.deputyId}`,deputyId:x.deputyId,date:v.date,kind:x.seat==='-1'?'remote_participation':'in_person_participation',value:'recorded_vote',voteId:v.id,seat:x.seat,evidenceUrl:v.url}))); 
const sessions=[...new Map(interventionRaw.map(x=>{const [day,month,year]=String(x.SESION||'').split('/');return [`${x.ORGANO}-${year}-${month}-${day}`,{id:`${x.ORGANO}-${year}-${month}-${day}`,body:x.ORGANO,date:year&&month&&day?`${year}-${month}-${day}`:x.SESION,status:'intervention_indexed'}]})).values()];
const interventions=interventionRaw.map((x,i)=>{const speaker=String(x.ORADOR||'').replace(/\s*\([^)]*\)\s*$/,'').toLocaleLowerCase('es');const [day,month,year]=String(x.SESION||'').split('/');return {id:`intervention-${i+1}`,sessionId:`${x.ORGANO}-${year}-${month}-${day}`,deputyId:byName.get(speaker)||null,speaker:x.ORADOR,initiativeId:x.NUMEXPEDIENTE||null,title:x.OBJETO||x.OBJETOINICIATIVA||x.TIPOINICIATIVA||null,topic:x.SUPERTIPOINICIATIVA||x.TIPOINICIATIVA||'sin clasificar',start:x.INICIOINTERVENCION||null,end:x.FININTERVENCION||null,textUrl:x.ENLACETEXTOINTEGRO||null,clipUrl:x.ENLACEDESCARGADIRECTA||null,sourceUrl:x.ENLACEPDF||null,text:null,textStatus:'official_text_linked'};});
const bodies=[...new Set(interventionRaw.map(x=>x.ORGANO).filter(Boolean))].map(name=>({id:slug(name),name,sourceUrl:'https://www.congreso.es/es/opendata/organos',membershipStatus:'activity-derived'}));
const bodyActivity=[...new Map(interventionRaw.filter(x=>x.ORADOR).map(x=>[`${x.ORGANO}|${x.ORADOR}`,{bodyId:slug(x.ORGANO),deputyId:byName.get(String(x.ORADOR).replace(/\s*\([^)]*\)\s*$/,'').toLocaleLowerCase('es'))||null,deputyName:x.ORADOR,firstDate:x.SESION,lastDate:x.SESION,evidenceType:'intervention_in_body'}])).values()];
await writeFile('data/current.json',JSON.stringify({meta:{legislature:'XV',status:'current-legislature',generatedAt:new Date().toISOString(),coverage:`${deputies.length} deputies who are active or have served in XV; ${interventions.length} official intervention records, ${votePayloads.length} vote payloads and ${attendanceEvents.length} attendance events indexed`},deputies,bodies,bodyActivity,sessions,interventions,votes:votePayloads,presenceObservations:attendanceEvents},null,2)); console.log(`built ${deputies.length} deputies, ${interventions.length} interventions and ${votePayloads.length} votes`);
