import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { gunzipSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(fileURLToPath(import.meta.url));
let data; try { data = JSON.parse(await readFile(path.join(root, '../data/current.json'), 'utf8')); } catch { data = JSON.parse(await readFile(path.join(root, '../data/sample.json'), 'utf8')); }
try { data.videoPilotObservations=JSON.parse(await readFile(path.join(root,'../data/video-pilot-observations.json'),'utf8')).observations||[]; } catch { data.videoPilotObservations=[]; }
try { data.transcriptDocuments=JSON.parse(gunzipSync(await readFile(path.join(root,'../data/transcripts.json.gz')),'utf8')).documents||[]; } catch { data.transcriptDocuments=[]; }
try { data.topicEvidence=JSON.parse(await readFile(path.join(root,'../data/topic-evidence.json'),'utf8')).evidence||[]; } catch { data.topicEvidence=[]; }
try { const full=JSON.parse(gunzipSync(await readFile(path.join(root,'../data/votes-full.json.gz')),'utf8')); const byName=new Map(data.deputies.map(d=>[String(d.name||'').toLocaleLowerCase('es'),d.id])); data.votes=full.votes.map(v=>({...v,individual:(v.payload?.votaciones||[]).map(x=>({deputyId:byName.get(String(x.diputado||'').toLocaleLowerCase('es'))||null,name:x.diputado,choice:x.voto,seat:x.asiento,group:x.grupo}))})); data.presenceObservations=data.votes.flatMap(v=>v.individual.filter(x=>x.deputyId).map(x=>({id:`${v.id}-${x.deputyId}`,deputyId:x.deputyId,date:v.payload?.informacion?.fecha,kind:x.seat==='-1'?'remote_participation':'in_person_participation',value:'recorded_vote',voteId:v.id,seat:x.seat,evidenceUrl:v.url}))); data.meta.coverage=data.meta.coverage.replace(/\d+ vote payloads/,`${data.votes.length} vote payloads`); data.meta.coverage=`${data.meta.coverage}; ${data.votes.length} ballots backfilled across ${full.meta.calendarDates} voting dates`;} catch { /* optional full vote archive */ }
const esc = (s='') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json = (res, body) => { res.writeHead(200, {'content-type':'application/json; charset=utf-8','cache-control':'no-store'}); res.end(JSON.stringify(body)); };
const page = (title, body) => `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(title)} · Congreso tracker</title><style>body{font:16px system-ui;max-width:1100px;margin:0 auto;padding:24px;background:#f7f4ed;color:#202020}a{color:#8d1c22}nav{display:flex;gap:18px;flex-wrap:wrap;border-bottom:1px solid #bbb;padding-bottom:14px;margin-bottom:28px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px}.card{background:white;border:1px solid #ccc;padding:16px}small,.muted{color:#666}table{border-collapse:collapse;width:100%;background:white}td,th{padding:9px;border-bottom:1px solid #ddd;text-align:left}.badge{font:12px monospace;background:#eee;padding:3px 6px}pre{white-space:pre-wrap;background:white;border:1px solid #ddd;padding:14px}</style><nav><a href="/">Congreso tracker</a><a href="/diputados">Diputados</a><a href="/sesiones">Sesiones</a><a href="/iniciativas">Iniciativas</a><a href="/transcritos">Transcritos</a><a href="/sustituciones">Sustituciones</a><a href="/organos">Órganos</a><a href="/votaciones">Votaciones</a><a href="/presencia">Presencia</a><a href="/api/congreso/v1/">API</a></nav>${body}`;
const minutes=(start,end)=>{if(!start||!end)return 0;const a=String(start).split(':').map(Number),b=String(end).split(':').map(Number);return Math.max(0,(b[0]*60+b[1])-(a[0]*60+a[1]));};
const dailyEvidence=(id)=>{const rows=new Map();for(const x of data.interventions.filter(i=>i.deputyId===id)){const s=data.sessions.find(v=>v.id===x.sessionId);const key=s?.date||'fecha desconocida';const row=rows.get(key)||{date:key,turns:0,minutes:0,intervals:[]};row.turns++;row.minutes+=minutes(x.start,x.end);if(x.start&&x.end)row.intervals.push(`${x.start}–${x.end}`);rows.set(key,row);}return [...rows.values()].sort((a,b)=>a.date.localeCompare(b.date));};
const metrics = d => {const iv=data.interventions.filter(x=>x.deputyId===d.id);return {speechTurns:iv.length,speakingDays:new Set(iv.map(x=>data.sessions.find(s=>s.id===x.sessionId)?.date)).size,evidencedMinutes:iv.reduce((n,x)=>n+minutes(x.start,x.end),0),votesRecorded:data.votes.reduce((n,v)=>n+v.individual.filter(x=>x.deputyId===d.id).length,0),presenceEvidence:data.presenceObservations.filter(x=>x.deputyId===d.id).length};};
function csv(rows){return rows.map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\n');}
const server=http.createServer(async (req,res)=>{const url=new URL(req.url,'http://localhost'); const p=url.pathname;
 if(p==='/api/congreso/v1/'||p==='/api/congreso/v1') return json(res,{meta:data.meta,resources:['deputies','service-periods','substitutions','profile-documents','hemicycle-seats','bodies','body-activity','formal-body-memberships','sessions','agenda-items','initiatives','initiative-authorship','interventions','media-segments','transcript-documents','topic-evidence','votes','presence-observations','video-pilot-observations','source-documents'],caveat:'Absence is never inferred from missing records.'});
 if(p.startsWith('/api/congreso/v1/')){const key=p.split('/').at(-1); const map={'deputies':'deputies','service-periods':'servicePeriods','substitutions':'substitutions','profile-documents':'profileDocuments','hemicycle-seats':'hemicycleSeats','bodies':'bodies','body-activity':'bodyActivity','formal-body-memberships':'formalBodyMemberships','sessions':'sessions','agenda-items':'agendaItems','initiatives':'initiatives','initiative-authorship':'initiativeAuthorship','interventions':'interventions','media-segments':'mediaSegments','transcript-documents':'transcriptDocuments','topic-evidence':'topicEvidence','votes':'votes','presence-observations':'presenceObservations','video-pilot-observations':'videoPilotObservations','source-documents':'sourceDocuments'}; if(!map[key]) return res.writeHead(404).end(); const rows=data[map[key]]||[]; const pageNo=Math.max(1,Number(url.searchParams.get('page')||1)); const pageSize=Math.min(1000,Math.max(1,Number(url.searchParams.get('pageSize')||100))); const start=(pageNo-1)*pageSize; return json(res,{meta:data.meta,data:rows.slice(start,start+pageSize),pagination:{page:pageNo,pageSize,total:rows.length,pages:Math.ceil(rows.length/pageSize)}});}
 if(p==='/diputados'){const q=(url.searchParams.get('q')||'').toLocaleLowerCase('es'); const ds=data.deputies.filter(d=>!q||`${d.name} ${d.group} ${d.constituency}`.toLocaleLowerCase('es').includes(q)); return res.end(page('Diputados',`<h1>Diputados · XV Legislatura</h1><p class="muted">${esc(data.meta.coverage)}</p><form><input name="q" value="${esc(q)}" placeholder="Buscar nombre, grupo o circunscripción"><button>Buscar</button></form><p><a href="/comparar">Comparar actividad →</a> · <a href="/export/deputies.csv">CSV</a></p><div class="grid">${ds.map(d=>{const m=metrics(d);return `<article class="card"><h2><a href="/diputados/${esc(d.id)}">${esc(d.name)}</a></h2><p>${esc(d.group)} · ${esc(d.constituency)}</p><small>Servicio: ${esc(d.service.from)} — ${d.service.to||'actualidad'}</small><div style="margin-top:12px" aria-label="${m.speechTurns} turnos, ${m.presenceEvidence} observaciones"><span class="badge">${m.speechTurns} interv.</span> <span class="badge">${m.presenceEvidence} presencia</span></div></article>`}).join('')}</div>`));}
 if(p==='/comparar'){const rows=data.deputies.map(d=>{const m=metrics(d);return `<tr><td><a href="/diputados/${esc(d.id)}">${esc(d.name)}</a></td><td>${esc(d.group)}</td><td><div style="background:#eee;height:12px;width:180px"><div style="background:#8d1c22;height:12px;width:${Math.min(100,m.speechTurns*45)}px"></div></div></td><td>${m.speechTurns}</td><td>${m.speakingDays}</td><td>${m.votesRecorded}</td><td>${m.presenceEvidence}</td></tr>`}).join(''); return res.end(page('Comparar',`<h1>Comparar actividad</h1><p class="muted">Comparación descriptiva de registros observados; no es una puntuación de dedicación. Los ceros pueden significar que el dato aún no se ha importado.</p><table><tr><th>Diputado</th><th>Grupo</th><th>Intervenciones</th><th>Turnos</th><th>Días</th><th>Votos</th><th>Evidencia presencia</th></tr>${rows}</table><p><a href="/api/congreso/v1/deputies">Descargar JSON completo →</a></p>`));}
 if(p.startsWith('/diputados/')){const d=data.deputies.find(x=>x.id===p.split('/').at(-1)); if(!d)return res.writeHead(404).end('No encontrado'); const m=metrics(d), iv=data.interventions.filter(x=>x.deputyId===d.id), daily=dailyEvidence(d.id); return res.end(page(d.name,`<p><a href="/diputados">← Diputados</a></p><h1>${esc(d.name)}</h1><p>${esc(d.group)} · ${esc(d.constituency)} · <a href="${esc(d.profileUrl||d.sourceUrl)}">ficha oficial</a></p><div class="grid"><div class="card"><b>${m.speechTurns}</b><br>turnos de intervención</div><div class="card"><b>${m.speakingDays}</b><br>días con intervención</div><div class="card"><b>${m.evidencedMinutes}</b><br>minutos con presencia temporal evidenciada</div><div class="card"><b>${m.votesRecorded}</b><br>votos individuales importados</div></div><h2>Tiempo evidenciado por día</h2><table><tr><th>Fecha</th><th>Turnos</th><th>Minutos</th><th>Intervalos publicados</th></tr>${daily.map(x=>`<tr><td>${esc(x.date)}</td><td>${x.turns}</td><td>${x.minutes||'—'}</td><td>${esc(x.intervals.join(', ')||'Sin hora')}</td></tr>`).join('')}</table><h2>Actividad</h2><table><tr><th>Sesión</th><th>Asunto</th><th>Tema</th><th>Hora</th><th>Evidencia</th></tr>${iv.slice(0,500).map(x=>`<tr><td>${esc(x.sessionId)}</td><td>${esc(x.title)}</td><td><span class="badge">${esc(x.topic)}</span></td><td>${esc(x.start||'')}–${esc(x.end||'')}</td><td>${x.clipUrl?`<a href="${esc(x.clipUrl)}">clip oficial</a>`:'transcripción'}</td></tr>`).join('')}</table><p class="muted">Los minutos son un límite inferior basado en intervenciones con hora de inicio y fin. No representan el tiempo total en el edificio o hemiciclo. Un voto remoto, una silla vacía o la ausencia de una intervención no prueban por sí solos presencia o ausencia física.</p>`));}
 if(p==='/sesiones'){return res.end(page('Sesiones',`<h1>Sesiones</h1><div class="grid">${data.sessions.map(s=>`<article class="card"><h2><a href="/sesiones/${esc(s.id)}">${esc(s.body)} ${s.number}</a></h2><p>${esc(s.date)} · ${esc(s.status)}</p></article>`).join('')}</div>`));}
 if(p==='/organos'){const counts=new Map(data.bodyActivity.map(x=>[x.bodyId,x]));return res.end(page('Órganos',`<h1>Órganos parlamentarios</h1><p class="muted">Actividad de sesiones e importaciones de composición formal. La constitución de comisiones puede producirse después de la publicación de esta página.</p><table><tr><th>Órgano</th><th>Sesiones</th><th>Intervenciones</th><th>Composición importada</th></tr>${data.bodies.map(b=>{const c=counts.get(b.id)||{};const n=data.formalBodyMemberships.filter(x=>x.bodyId===b.id).length;return `<tr><td>${esc(b.name)}</td><td>${c.sessions||0}</td><td>${c.interventions||0}</td><td>${n||'—'}</td></tr>`}).join('')}</table><p><a href="/api/congreso/v1/bodies">JSON de órganos</a> · <a href="/api/congreso/v1/formal-body-memberships">JSON de composiciones</a></p>`));}
 if(p==='/iniciativas'){const counts=new Map();for(const x of data.interventions){if(x.initiativeId)counts.set(x.initiativeId,(counts.get(x.initiativeId)||0)+1);}return res.end(page('Iniciativas',`<h1>Iniciativas y asuntos</h1><p class="muted">${data.initiatives.length} iniciativas deduplicadas desde los registros oficiales de intervención. El vínculo de autoría distingue a quien intervino de quien presentó una iniciativa.</p><table><tr><th>Expediente</th><th>Título</th><th>Tipo</th><th>Autor publicado</th><th>Intervenciones vinculadas</th><th>Fuente</th></tr>${data.initiatives.slice(0,1000).map(x=>`<tr><td>${esc(x.number||x.id)}</td><td>${esc(x.title||'—')}</td><td>${esc(x.type||x.superType||'—')}</td><td>${esc(x.authorLabel||'—')}</td><td>${counts.get(x.id)||0}</td><td>${x.sourceUrl?`<a href="${esc(x.sourceUrl)}">oficial</a>`:'—'}</td></tr>`).join('')}</table><p class="muted">Se muestran las primeras 1.000 filas; <a href="/api/congreso/v1/initiatives?pageSize=1000">API paginado</a>.</p>`));}
 if(p==='/votaciones'){return res.end(page('Votaciones',`<h1>Votaciones nominales</h1><p class="muted">${data.votes.length} votaciones descargadas de los días publicados por el Congreso. “Telemático” se conserva como participación remota y no como presencia física.</p><table><tr><th>Fecha</th><th>Sesión</th><th>Votación</th><th>Presentes</th><th>A favor</th><th>En contra</th><th>Abstenciones</th><th>Fuente</th></tr>${data.votes.slice(0,1000).map(v=>{const i=v.payload?.informacion||{},t=v.payload?.totales||{};return `<tr><td>${esc(i.fecha)}</td><td>${esc(i.sesion)}</td><td>${esc(i.numeroVotacion||v.id)}</td><td>${t.presentes??'—'}</td><td>${t.afavor??'—'}</td><td>${t.enContra??'—'}</td><td>${t.abstenciones??'—'}</td><td><a href="${esc(v.url)}">oficial</a></td></tr>`}).join('')}</table><p class="muted">Se muestran las primeras 1.000 filas; el <a href="/api/congreso/v1/votes?pageSize=1000">API paginado</a> permite consultar el archivo completo.</p>`));}
 if(p==='/presencia'){const reviewed=data.videoPilotObservations.filter(x=>x.reviewStatus==='reviewed').length;const usable=data.videoPilotObservations.filter(x=>x.value!=='unobservable').length;return res.end(page('Presencia',`<h1>Evidencia de presencia</h1><div class="grid"><div class="card"><b>${data.presenceObservations.length}</b><br>eventos de voto atribuidos</div><div class="card"><b>${data.videoPilotObservations.length}</b><br>observaciones de asiento del piloto</div><div class="card"><b>${usable}</b><br>observaciones observables</div><div class="card"><b>${reviewed}</b><br>observaciones revisadas</div></div><p class="muted">Una observación de asiento solo describe si el lugar era observable; no identifica automáticamente al diputado. Una silla vacía, un voto perdido o una cámara fuera de plano no prueban ausencia.</p><p><a href="/api/congreso/v1/presence-observations">Eventos nominales</a> · <a href="/api/congreso/v1/video-pilot-observations">Piloto de vídeo</a></p>`));}
 if(p==='/hemiciclo'){return res.end(page('Hemiciclo',`<h1>Mapa del hemiciclo</h1><p class="muted">${data.hemicycleSeats.length} posiciones identificadas desde el mapa oficial actual. Este mapa está fechado en la captura y no se aplica retrospectivamente a sesiones anteriores.</p><p><img src="https://www.congreso.es/o/diputados/img/hemiciclo.png" alt="Mapa oficial del hemiciclo" style="max-width:100%;height:auto"></p><table><tr><th>Identificador oficial</th><th>Etiqueta</th><th>Coordenadas</th></tr>${data.hemicycleSeats.map(x=>`<tr><td>${esc(x.officialId)}</td><td>${esc(x.label)}</td><td>${esc(x.coords)}</td></tr>`).join('')}</table><p><a href="/api/congreso/v1/hemicycle-seats">JSON de posiciones</a></p>`));}
 if(p==='/sustituciones'){return res.end(page('Sustituciones',`<h1>Sustituciones</h1><p class="muted">${data.substitutions.length} relaciones publicadas por el Congreso para la XV Legislatura. Las fechas se conservan tal como aparecen en la fuente.</p><table><tr><th>Diputado sustituido</th><th>Sustituto</th><th>Alta</th><th>Baja</th></tr>${data.substitutions.map(x=>`<tr><td>${esc(x.substitutedName||x.substitutedId||'—')}</td><td>${esc(x.substituteName||x.substituteId||'—')}</td><td>${esc(x.from||'—')}</td><td>${esc(x.to||'—')}</td></tr>`).join('')}</table><p><a href="/api/congreso/v1/substitutions">JSON completo</a></p>`));}
 if(p==='/transcritos'){const q=(url.searchParams.get('q')||'').toLocaleLowerCase('es');const docs=data.transcriptDocuments.filter(x=>!q||String(x.text||'').toLocaleLowerCase('es').includes(q)||x.url.toLocaleLowerCase('es').includes(q));return res.end(page('Transcritos',`<h1>Diarios de Sesiones</h1><p class="muted">${data.transcriptDocuments.filter(x=>x.text).length} documentos con texto oficial extraído. Las búsquedas se realizan sobre el texto original conservado.</p><form><input name="q" value="${esc(q)}" placeholder="Buscar en transcritos"><button>Buscar</button></form><table><tr><th>Estado</th><th>Documento oficial</th><th>Caracteres</th><th>Texto</th></tr>${docs.slice(0,200).map(x=>`<tr><td>${esc(x.textStatus)}</td><td><a href="${esc(x.url)}">fuente</a></td><td>${x.text?.length||0}</td><td>${x.text?`<details><summary>Ver pasaje</summary><pre>${esc(x.text.slice(0,1400))}</pre></details>`:'—'}</td></tr>`).join('')}</table><p class="muted">Se muestran hasta 200 resultados. <a href="/api/congreso/v1/transcript-documents?pageSize=1000">API completo</a>.</p>`));}
 if(p.startsWith('/sesiones/')){const s=data.sessions.find(x=>x.id===p.split('/').at(-1));if(!s)return res.writeHead(404).end('No encontrada');const iv=data.interventions.filter(x=>x.sessionId===s.id);return res.end(page(`Sesión ${s.number}`,`<h1>${esc(s.body)} ${s.number}</h1><p>${esc(s.date)} · <a href="${esc(s.agendaUrl)}">orden del día</a> · <a href="${esc(s.videoUrl)}">índice audiovisual</a></p><h2>Intervenciones indexadas</h2><table><tr><th>Diputado</th><th>Asunto</th><th>Tema</th><th>Clip</th></tr>${iv.map(x=>`<tr><td><a href="/diputados/${esc(x.deputyId)}">${esc(data.deputies.find(d=>d.id===x.deputyId)?.name||x.deputyId)}</a></td><td>${esc(x.title)}</td><td>${esc(x.topic)}</td><td><a href="${esc(x.clipUrl)}">MP4</a></td></tr>`).join('')}</table><p class="muted">Agenda, acta/transcripción, vídeo y votos se mantienen como fuentes distintas.</p>`));}
 if(p==='/export/deputies.csv'){res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="diputados-xv.csv"'}); return res.end(csv([['id','name','group','constituency','service_from','service_to'],...data.deputies.map(d=>[d.id,d.name,d.group,d.constituency,d.service.from,d.service.to])]));}
 if(p==='/export/interventions.csv'){res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="intervenciones-xv.csv"'});return res.end(csv([['id','session_id','deputy_id','initiative_id','title','topic','start','end','text_url','clip_url'],...data.interventions.map(x=>[x.id,x.sessionId,x.deputyId,x.initiativeId,x.title,x.topic,x.start,x.end,x.textUrl,x.clipUrl])]));}
 if(p==='/export/votes.csv'){res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="votaciones-xv.csv"'});return res.end(csv([['id','date','session','vote_number','presentes','afavor','enContra','abstenciones'],...data.votes.map(v=>{const i=v.payload?.informacion||{},t=v.payload?.totales||{};return[v.id,i.fecha,i.sesion,i.numeroVotacion,t.presentes,t.afavor,t.enContra,t.abstenciones]})]));}
 return res.end(page('Inicio',`<h1>Participación parlamentaria, con evidencia</h1><p>Panel visual para explorar quién interviene, sobre qué asuntos, cómo vota y qué presencia puede demostrarse. La versión incluida es un fixture de validación; cada registro conserva su fuente y estado de cobertura.</p><div class="grid"><div class="card"><h2>${data.deputies.length}</h2><p>diputados cargados</p></div><div class="card"><h2>${data.sessions.length}</h2><p>sesiones indexadas</p></div><div class="card"><h2>${data.interventions.length}</h2><p>intervenciones con clip</p></div><div class="card"><h2>${data.votes.length}</h2><p>votaciones</p></div></div><p><a href="/diputados">Explorar diputados →</a> · <a href="/comparar">Ver comparativa →</a> · <a href="/sesiones">Ver sesiones →</a></p><h2>Actividad por diputado</h2><table><tr><th>Diputado</th><th>Grupo</th><th>Intervenciones</th><th>Votos registrados</th><th>Presencia evidenciada</th></tr>${data.deputies.map(d=>{const m=metrics(d);return `<tr><td><a href="/diputados/${esc(d.id)}">${esc(d.name)}</a></td><td>${esc(d.group)}</td><td>${m.speechTurns}</td><td>${m.votesRecorded}</td><td>${m.presenceEvidence}</td></tr>`}).join('')}</table><h2>Qué significa presencia</h2><p>Intervención presencial, voto telemático, asistencia oficial y observaciones de asiento se visualizan por separado. Lo desconocido permanece desconocido.</p>`));
});
server.listen(process.env.PORT||8787,()=>console.log(`Congress tracker listening on http://localhost:${process.env.PORT||8787}`));
