import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(await readFile(path.join(root, '../data/sample.json'), 'utf8'));
const esc = (s='') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json = (res, body) => { res.writeHead(200, {'content-type':'application/json; charset=utf-8','cache-control':'no-store'}); res.end(JSON.stringify(body)); };
const page = (title, body) => `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(title)} · Congreso tracker</title><style>body{font:16px system-ui;max-width:1100px;margin:0 auto;padding:24px;background:#f7f4ed;color:#202020}a{color:#8d1c22}nav{display:flex;gap:18px;border-bottom:1px solid #bbb;padding-bottom:14px;margin-bottom:28px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px}.card{background:white;border:1px solid #ccc;padding:16px}small,.muted{color:#666}table{border-collapse:collapse;width:100%;background:white}td,th{padding:9px;border-bottom:1px solid #ddd;text-align:left}.badge{font:12px monospace;background:#eee;padding:3px 6px}</style><nav><a href="/">Congreso tracker</a><a href="/diputados">Diputados</a><a href="/sesiones">Sesiones</a><a href="/api/congreso/v1/">API</a></nav>${body}`;
const metrics = d => ({speechTurns:data.interventions.filter(x=>x.deputyId===d.id).length, speakingDays:new Set(data.interventions.filter(x=>x.deputyId===d.id).map(x=>data.sessions.find(s=>s.id===x.sessionId)?.date)).size, votesRecorded:data.votes.reduce((n,v)=>n+v.individual.filter(x=>x.deputyId===d.id).length,0), presenceEvidence:data.presenceObservations.filter(x=>x.deputyId===d.id).length});
function csv(rows){return rows.map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\n');}
const server=http.createServer(async (req,res)=>{const url=new URL(req.url,'http://localhost'); const p=url.pathname;
 if(p==='/api/congreso/v1/'||p==='/api/congreso/v1') return json(res,{meta:data.meta,resources:['deputies','sessions','interventions','votes','presence-observations'],caveat:'Absence is never inferred from missing records.'});
 if(p.startsWith('/api/congreso/v1/')){const key=p.split('/').at(-1); const map={'deputies':'deputies','sessions':'sessions','interventions':'interventions','votes':'votes','presence-observations':'presenceObservations'}; if(!map[key]) return res.writeHead(404).end(); return json(res,{meta:data.meta,data:data[map[key]],pagination:{page:1,pageSize:data[map[key]].length,total:data[map[key]].length}});}
 if(p==='/diputados'){const q=(url.searchParams.get('q')||'').toLocaleLowerCase('es'); const ds=data.deputies.filter(d=>!q||`${d.name} ${d.group} ${d.constituency}`.toLocaleLowerCase('es').includes(q)); return res.end(page('Diputados',`<h1>Diputados · XV Legislatura</h1><p class="muted">${esc(data.meta.coverage)}</p><form><input name="q" value="${esc(q)}" placeholder="Buscar nombre, grupo o circunscripción"><button>Buscar</button></form><p><a href="/comparar">Comparar actividad →</a> · <a href="/export/deputies.csv">CSV</a></p><div class="grid">${ds.map(d=>{const m=metrics(d);return `<article class="card"><h2><a href="/diputados/${esc(d.id)}">${esc(d.name)}</a></h2><p>${esc(d.group)} · ${esc(d.constituency)}</p><small>Servicio: ${esc(d.service.from)} — ${d.service.to||'actualidad'}</small><div style="margin-top:12px" aria-label="${m.speechTurns} turnos, ${m.presenceEvidence} observaciones"><span class="badge">${m.speechTurns} interv.</span> <span class="badge">${m.presenceEvidence} presencia</span></div></article>`}).join('')}</div>`));}
 if(p==='/comparar'){const rows=data.deputies.map(d=>{const m=metrics(d);return `<tr><td><a href="/diputados/${esc(d.id)}">${esc(d.name)}</a></td><td>${esc(d.group)}</td><td><div style="background:#eee;height:12px;width:180px"><div style="background:#8d1c22;height:12px;width:${Math.min(100,m.speechTurns*45)}px"></div></div></td><td>${m.speechTurns}</td><td>${m.speakingDays}</td><td>${m.votesRecorded}</td><td>${m.presenceEvidence}</td></tr>`}).join(''); return res.end(page('Comparar',`<h1>Comparar actividad</h1><p class="muted">Comparación descriptiva de registros observados; no es una puntuación de dedicación. Los ceros pueden significar que el dato aún no se ha importado.</p><table><tr><th>Diputado</th><th>Grupo</th><th>Intervenciones</th><th>Turnos</th><th>Días</th><th>Votos</th><th>Evidencia presencia</th></tr>${rows}</table><p><a href="/api/congreso/v1/deputies">Descargar JSON completo →</a></p>`));}
 if(p.startsWith('/diputados/')){const d=data.deputies.find(x=>x.id===p.split('/').at(-1)); if(!d)return res.writeHead(404).end('No encontrado'); const m=metrics(d), iv=data.interventions.filter(x=>x.deputyId===d.id); return res.end(page(d.name,`<p><a href="/diputados">← Diputados</a></p><h1>${esc(d.name)}</h1><p>${esc(d.group)} · ${esc(d.constituency)} · <a href="${esc(d.profileUrl)}">ficha oficial</a></p><div class="grid"><div class="card"><b>${m.speechTurns}</b><br>turnos de intervención</div><div class="card"><b>${m.speakingDays}</b><br>días con intervención</div><div class="card"><b>${m.votesRecorded}</b><br>votos individuales importados</div><div class="card"><b>${m.presenceEvidence}</b><br>observaciones de presencia</div></div><h2>Actividad</h2><table><tr><th>Sesión</th><th>Asunto</th><th>Tema</th><th>Evidencia</th></tr>${iv.map(x=>`<tr><td>${esc(x.sessionId)}</td><td>${esc(x.title)}</td><td><span class="badge">${esc(x.topic)}</span></td><td><a href="${esc(x.clipUrl)}">clip oficial</a></td></tr>`).join('')}</table><p class="muted">Las métricas son de cobertura observada. Un voto remoto, una silla vacía o la ausencia de una intervención no prueban por sí solos presencia o ausencia física.</p>`));}
 if(p==='/sesiones'){return res.end(page('Sesiones',`<h1>Sesiones</h1><div class="grid">${data.sessions.map(s=>`<article class="card"><h2><a href="/sesiones/${esc(s.id)}">${esc(s.body)} ${s.number}</a></h2><p>${esc(s.date)} · ${esc(s.status)}</p></article>`).join('')}</div>`));}
 if(p.startsWith('/sesiones/')){const s=data.sessions.find(x=>x.id===p.split('/').at(-1));if(!s)return res.writeHead(404).end('No encontrada');const iv=data.interventions.filter(x=>x.sessionId===s.id);return res.end(page(`Sesión ${s.number}`,`<h1>${esc(s.body)} ${s.number}</h1><p>${esc(s.date)} · <a href="${esc(s.agendaUrl)}">orden del día</a> · <a href="${esc(s.videoUrl)}">índice audiovisual</a></p><h2>Intervenciones indexadas</h2><table><tr><th>Diputado</th><th>Asunto</th><th>Tema</th><th>Clip</th></tr>${iv.map(x=>`<tr><td><a href="/diputados/${esc(x.deputyId)}">${esc(data.deputies.find(d=>d.id===x.deputyId)?.name||x.deputyId)}</a></td><td>${esc(x.title)}</td><td>${esc(x.topic)}</td><td><a href="${esc(x.clipUrl)}">MP4</a></td></tr>`).join('')}</table><p class="muted">Agenda, acta/transcripción, vídeo y votos se mantienen como fuentes distintas.</p>`));}
 if(p==='/export/deputies.csv'){res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="diputados-xv.csv"'}); return res.end(csv([['id','name','group','constituency','service_from','service_to'],...data.deputies.map(d=>[d.id,d.name,d.group,d.constituency,d.service.from,d.service.to])]));}
 return res.end(page('Inicio',`<h1>Participación parlamentaria, con evidencia</h1><p>Panel visual para explorar quién interviene, sobre qué asuntos, cómo vota y qué presencia puede demostrarse. La versión incluida es un fixture de validación; cada registro conserva su fuente y estado de cobertura.</p><div class="grid"><div class="card"><h2>${data.deputies.length}</h2><p>diputados cargados</p></div><div class="card"><h2>${data.sessions.length}</h2><p>sesiones indexadas</p></div><div class="card"><h2>${data.interventions.length}</h2><p>intervenciones con clip</p></div><div class="card"><h2>${data.votes.length}</h2><p>votaciones</p></div></div><p><a href="/diputados">Explorar diputados →</a> · <a href="/comparar">Ver comparativa →</a> · <a href="/sesiones">Ver sesiones →</a></p><h2>Actividad por diputado</h2><table><tr><th>Diputado</th><th>Grupo</th><th>Intervenciones</th><th>Votos registrados</th><th>Presencia evidenciada</th></tr>${data.deputies.map(d=>{const m=metrics(d);return `<tr><td><a href="/diputados/${esc(d.id)}">${esc(d.name)}</a></td><td>${esc(d.group)}</td><td>${m.speechTurns}</td><td>${m.votesRecorded}</td><td>${m.presenceEvidence}</td></tr>`}).join('')}</table><h2>Qué significa presencia</h2><p>Intervención presencial, voto telemático, asistencia oficial y observaciones de asiento se visualizan por separado. Lo desconocido permanece desconocido.</p>`));
});
server.listen(process.env.PORT||8787,()=>console.log(`Congress tracker listening on http://localhost:${process.env.PORT||8787}`));
